
spring.application.name=Backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springtercash?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pa$$w0rd

# Muestra las sentencias SQL generadas por Hibernate en la consola. ?til para depuraci?n.
spring.jpa.show-sql=true

# Formatea las sentencias SQL mostradas por 'show-sql' para que sean m?s legibles.
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=embedded

spring.sql.init.schema-locations=classpath:db.sql
spring.sql.init.data-locations=classpath:data.sql
